# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true           # pour autoriser les cookies ou JWT si n√©cessaire
        allow_origin: ['http://localhost:3000']  # ton front
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
